apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sok-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sok-api
  minReplicas: 2
  maxReplicas: 20
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sok-socket
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sok-socket
  minReplicas: 3
  maxReplicas: 40
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
