pekko {
  loglevel = "INFO"
  
  actor {
    provider = "cluster"
    
    serialization-bindings {
      "com.sok.backend.realtime.actor.RoomCommand" = jackson-json
      "com.sok.backend.realtime.actor.RoomCommand$RoomEvent" = jackson-json
      "com.sok.backend.realtime.domain.GameState" = jackson-json
    }
  }

  remote.artery {
    canonical {
      hostname = "127.0.0.1"
      port = 25520
    }
  }

  cluster {
    seed-nodes = ["pekko://SokRealtimeSystem@127.0.0.1:25520"]
    
    downing-provider-class = "org.apache.pekko.cluster.sbr.SplitBrainResolverProvider"
    
    sharding {
      number-of-shards = 100
      entity-recovery-strategy = "constant"
      entity-recovery-constant-rate-strategy {
        frequency = 100ms
        number-of-entities = 1
      }
    }
  }

  http {
    server {
      websocket {
        periodic-keep-alive-max-idle = 30s
      }
    }
  }
}
